// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAWAQGxzzfLB34T2CQC5eWz13kwXJPyaLM',
    appId: '1:171284768402:web:b0b5a794789e702c32a84b',
    messagingSenderId: '171284768402',
    projectId: 'cargo-a76eb',
    authDomain: 'cargo-a76eb.firebaseapp.com',
    storageBucket: 'cargo-a76eb.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAf8CrFxMAkj3hS8BDOijtDf_DpoZ2HImA',
    appId: '1:171284768402:android:0095133e0650f12f32a84b',
    messagingSenderId: '171284768402',
    projectId: 'cargo-a76eb',
    storageBucket: 'cargo-a76eb.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAWAQGxzzfLB34T2CQC5eWz13kwXJPyaLM',
    appId: '1:171284768402:web:0ce9d756fc2e690332a84b',
    messagingSenderId: '171284768402',
    projectId: 'cargo-a76eb',
    authDomain: 'cargo-a76eb.firebaseapp.com',
    storageBucket: 'cargo-a76eb.firebasestorage.app',
  );
}
